name = "TreeSL"
grammar = "treesl"
path_suffixes = ["grammarfile", "treesl"]
line_comments = [";"]
autoclose_before = "}])"
brackets = [
  { start = "{", end = "}", close = true, newline = false },
  { start = "[", end = "]", close = true, newline = false },
  { start = "(", end = ")", close = true, newline = false },
  { start = "\"", end = "\"", close = true, newline = false, not_in = [
    "string",
  ] },
]
